version: '3'

services:
  php:
    # ./docker/phpの内容(Dockerfile,php.ini,000-default)でphpコンテナ作成する
    build: ./docker/php
    # ./srcと/var/wwwをマウント。./srcと/var/wwwの変更内容が同期される。
    volumes:
      - ./src:/var/www
    # 使用するポート番号を指定
    ports:
      - 8080:80
      - 8081:81
    # コンテナ名を指定
    container_name: laravel_php

  # laravelの設定の際に、DB_HOSTとして指定される
  mysql:
    image: mysql:8.0
    # mysql8の認証プラグイン。この記述がないと弾かれる。
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    ports:
        # ${DB_PORT}と.envのWEB_PORTが対応
        - 3306:3306
    environment:
        MYSQL_DATABASE: emergency
        MYSQL_USER: ecc
        MYSQL_ROOT_PASSWORD: ecc
        MYSQL_PASSWORD: ecc
    container_name: laravel_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql #mysqlサービス名を指定
      - PMA_USER=ecc
      - PMA_PASSWORD=ecc
    links:
      - mysql
    ports:
      - 8888:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    container_name: laravel_pma
